# Generated by Django 5.2.8 on 2025-12-25 04:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Generated context content')),
                ('original_content', models.TextField(blank=True, help_text='Original content before refinement')),
                ('review_feedback', models.TextField(blank=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('iteration_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contexts',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.IntegerField(default=100, help_text='Number of question generation credits remaining', validators=[django.core.validators.MinValueValidator(0)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='source_files/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, help_text='OCR/extracted text content for reuse')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedMedia',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('media_file', models.ImageField(upload_to='extracted_media/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('chart', 'Chart/Graph'), ('table', 'Table Image'), ('diagram', 'Diagram')], max_length=20)),
                ('context_snippet', models.TextField(blank=True, help_text='Surrounding text for context/search')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_media', to='genmcq.sourcefile')),
            ],
            options={
                'verbose_name_plural': 'Extracted Media',
                'db_table': 'extracted_media',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('text', 'Direct Text Input'), ('file', 'Uploaded File'), ('url', 'URL')], default='text', max_length=10)),
                ('source_text', models.TextField(blank=True, help_text='Direct text input or extracted text')),
                ('source_url', models.URLField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Normalized difficulty (easy/medium/hard)', max_length=10)),
                ('bloom_level', models.CharField(choices=[('Remember', 'Remember'), ('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], default='Understand', max_length=20)),
                ('number_questions', models.IntegerField(default=5, help_text='Target number of questions to generate', validators=[django.core.validators.MinValueValidator(1)])),
                ('key_points', models.TextField(blank=True, help_text='Key points to focus on')),
                ('exercises', models.TextField(blank=True, help_text='Related exercises')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional generation config: model, max_iterations, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating_contexts', 'Generating Contexts'), ('reviewing_contexts', 'Reviewing Contexts'), ('generating_mcqs', 'Generating MCQs'), ('reviewing_mcqs', 'Reviewing MCQs'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('thread_id', models.CharField(blank=True, help_text='LangGraph thread ID for resuming', max_length=100)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('iteration_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='genmcq.sourcefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20)),
                ('stem', models.TextField(help_text='Question stem/content')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Normalized difficulty (easy/medium/hard)', max_length=10)),
                ('options', models.JSONField(default=list, help_text='[{"id": "A", "text": "...", "is_correct": false}, ...]')),
                ('correct_answer', models.CharField(help_text='Correct option ID (A, B, C, D)', max_length=10)),
                ('explanation', models.TextField(blank=True, help_text='Answer explanation')),
                ('reasoning', models.JSONField(blank=True, default=dict, help_text='Full reasoning: bloom_level_analysis, tactic_analysis, etc.')),
                ('review_feedback', models.TextField(blank=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('user_edited', models.BooleanField(default=False, help_text='True if user manually edited this question')),
                ('original_data', models.JSONField(blank=True, default=dict, help_text='Original AI-generated data before user edits')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(blank=True, help_text='Source context this question was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='genmcq.context')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='genmcq.extractedmedia')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='genmcq.subject')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('context_gen', 'Context Generation'), ('context_review', 'Context Review'), ('context_refine', 'Context Refinement'), ('mcq_gen', 'MCQ Generation'), ('mcq_review', 'MCQ Review'), ('mcq_refine', 'MCQ Refinement'), ('error', 'Error'), ('human_feedback', 'Human Feedback')], max_length=30)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='genmcq.subject')),
            ],
            options={
                'db_table': 'generation_logs',
                'ordering': ['subject', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='context',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='genmcq.subject'),
        ),
    ]
