# Generated by Django 5.2.8 on 2026-01-06 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmcq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(default='document', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='genmcq.sourcefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='genmcq.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoomAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoom_user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_type', models.CharField(default='basic', max_length=50)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('is_bot_account', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zoom_accounts',
            },
        ),
        migrations.CreateModel(
            name='ZoomBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_name', models.CharField(max_length=100)),
                ('bot_type', models.CharField(default='assistant', max_length=50)),
                ('capabilities', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('max_concurrent_sessions', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zoom_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='genmcq.zoomaccount')),
            ],
            options={
                'db_table': 'zoom_bots',
            },
        ),
        migrations.CreateModel(
            name='ZoomBotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('context_files', models.JSONField(default=list)),
                ('questions_answered', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='genmcq.zoombot')),
            ],
            options={
                'db_table': 'zoom_bot_sessions',
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(default='qa', max_length=20)),
                ('user_question', models.TextField(blank=True)),
                ('bot_response', models.TextField()),
                ('context_used', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='genmcq.zoombotsession')),
            ],
            options={
                'db_table': 'bot_messages',
            },
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoom_meeting_id', models.CharField(max_length=50, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('agenda', models.TextField(blank=True)),
                ('meeting_type', models.CharField(default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('join_url', models.URLField(max_length=500)),
                ('host_url', models.URLField(max_length=500)),
                ('waiting_room_enabled', models.BooleanField(default=False)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to=settings.AUTH_USER_MODEL)),
                ('zoom_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='genmcq.zoomaccount')),
            ],
            options={
                'db_table': 'zoom_meetings',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='zoombotsession',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='genmcq.zoommeeting'),
        ),
        migrations.CreateModel(
            name='ZoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='attendee', max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='genmcq.zoommeeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zoom_participants',
            },
        ),
        migrations.CreateModel(
            name='ZoomRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoom_recording_id', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('download_url', models.URLField(max_length=500)),
                ('play_url', models.URLField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='genmcq.zoommeeting')),
            ],
            options={
                'db_table': 'zoom_recordings',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='genmcq.zoomrecording'),
        ),
        migrations.CreateModel(
            name='ZoomTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('segments', models.JSONField(default=list)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='genmcq.zoommeeting')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='genmcq.zoomrecording')),
            ],
            options={
                'db_table': 'zoom_transcripts',
            },
        ),
    ]
