# Generated by Django 5.2.8 on 2026-01-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmcq', '0002_chatsession_chatmessage_credittransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomaccount',
            name='access_token',
            field=models.TextField(db_column='access_token'),
        ),
        migrations.RenameField(
            model_name='zoomaccount',
            old_name='access_token',
            new_name='_access_token',
        ),
        migrations.AlterField(
            model_name='zoomaccount',
            name='refresh_token',
            field=models.TextField(db_column='refresh_token'),
        ),
        migrations.RenameField(
            model_name='zoomaccount',
            old_name='refresh_token',
            new_name='_refresh_token',
        ),
    ]
