# Generated by Django 5.2.8 on 2026-01-06 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmcq', '0003_alter_zoomaccount_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zoomaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='zoom_account',
        ),
        migrations.RemoveField(
            model_name='zoombot',
            name='zoom_account',
        ),
        migrations.RemoveField(
            model_name='zoombotsession',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='zoombotsession',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='zoomrecording',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='zoomtranscript',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zoomtranscript',
            name='recording',
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='extractedmedia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.RemoveField(
            model_name='context',
            name='original_content',
        ),
        migrations.RemoveField(
            model_name='context',
            name='review_feedback',
        ),
        migrations.RemoveField(
            model_name='context',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='generationlog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='generationlog',
            name='tokens_used',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='context',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='context',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='context_snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='extracted_media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('table', 'Table'), ('chart', 'Chart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='generationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generationlog',
            name='log_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='genmcq.context'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genmcq.extractedmedia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('image', 'Image'), ('text', 'Text')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='bloom_level',
            field=models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exercises',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='key_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='number_questions',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genmcq.sourcefile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('url', 'URL')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='thread_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=100, verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('room_type', models.CharField(choices=[('community', 'Cộng đồng'), ('work', 'Công việc'), ('ai_deep', 'Chuyên sâu AI')], default='community', max_length=20, verbose_name='Loại phòng')),
                ('has_password', models.BooleanField(default=False, verbose_name='Có mật khẩu')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_enabled', models.BooleanField(default=True, verbose_name='Bật chatbot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phòng Chat',
                'verbose_name_plural': 'Phòng Chat',
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('role', models.CharField(choices=[('host', 'Host'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_typing', models.BooleanField(default=False)),
                ('typing_since', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='genmcq.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thành viên phòng',
                'verbose_name_plural': 'Thành viên phòng',
                'db_table': 'chat_room_members',
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoomFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file', models.FileField(upload_to='room_files/%Y/%m/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=10)),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Nội dung trích xuất')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='genmcq.chatroom')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_room_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File phòng',
                'verbose_name_plural': 'Files phòng',
                'db_table': 'room_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='genmcq.roomfile')),
            ],
            options={
                'verbose_name': 'Hội thoại file',
                'verbose_name_plural': 'Hội thoại file',
                'db_table': 'file_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_bot_message', models.BooleanField(default=False, verbose_name='Tin nhắn từ Bot')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='Tin nhắn hệ thống')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Đã ghim')),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='genmcq.roommessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='genmcq.chatroom')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhắn phòng',
                'verbose_name_plural': 'Tin nhắn phòng',
                'db_table': 'room_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BotMessage',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
        migrations.DeleteModel(
            name='ZoomAccount',
        ),
        migrations.DeleteModel(
            name='ZoomBot',
        ),
        migrations.DeleteModel(
            name='ZoomBotSession',
        ),
        migrations.DeleteModel(
            name='ZoomMeeting',
        ),
        migrations.DeleteModel(
            name='ZoomParticipant',
        ),
        migrations.DeleteModel(
            name='ZoomRecording',
        ),
        migrations.DeleteModel(
            name='ZoomTranscript',
        ),
    ]
