# Generated by Django 5.2.8 on 2026-01-06 09:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genmcq', '0004_remove_chatmessage_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['subject', 'order']},
        ),
        migrations.AlterModelOptions(
            name='extractedmedia',
            options={'verbose_name_plural': 'Extracted Media'},
        ),
        migrations.AlterModelOptions(
            name='generationlog',
            options={'ordering': ['subject', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['subject', 'order']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='context',
            name='original_content',
            field=models.TextField(blank=True, help_text='Original content before refinement'),
        ),
        migrations.AddField(
            model_name='context',
            name='review_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='context',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generationlog',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationlog',
            name='tokens_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Normalized difficulty (easy/medium/hard)', max_length=10),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='OCR/extracted text content for reuse'),
        ),
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Normalized difficulty (easy/medium/hard)', max_length=10),
        ),
        migrations.AlterField(
            model_name='context',
            name='content',
            field=models.TextField(help_text='Generated context content'),
        ),
        migrations.AlterField(
            model_name='context',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='context_snippet',
            field=models.TextField(blank=True, help_text='Surrounding text for context/search'),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='media_file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='extracted_media/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractedmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('chart', 'Chart/Graph'), ('table', 'Table Image'), ('diagram', 'Diagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generationlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generationlog',
            name='log_type',
            field=models.CharField(choices=[('context_gen', 'Context Generation'), ('context_review', 'Context Review'), ('context_refine', 'Context Refinement'), ('mcq_gen', 'MCQ Generation'), ('mcq_review', 'MCQ Review'), ('mcq_refine', 'MCQ Refinement'), ('error', 'Error'), ('human_feedback', 'Human Feedback')], max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.ForeignKey(blank=True, help_text='Source context this question was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='genmcq.context'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='Correct option ID (A, B, C, D)', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Answer explanation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='genmcq.extractedmedia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list, help_text='[{"id": "A", "text": "...", "is_correct": false}, ...]'),
        ),
        migrations.AlterField(
            model_name='question',
            name='original_data',
            field=models.JSONField(blank=True, default=dict, help_text='Original AI-generated data before user edits'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='reasoning',
            field=models.JSONField(blank=True, default=dict, help_text='Full reasoning: bloom_level_analysis, tactic_analysis, etc.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.TextField(help_text='Question stem/content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_edited',
            field=models.BooleanField(default=False, help_text='True if user manually edited this question'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('image', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='bloom_level',
            field=models.CharField(choices=[('Remember', 'Remember'), ('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], default='Understand', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional generation config: model, max_iterations, etc.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exercises',
            field=models.TextField(blank=True, help_text='Related exercises'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='key_points',
            field=models.TextField(blank=True, help_text='Key points to focus on'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='number_questions',
            field=models.IntegerField(default=5, help_text='Target number of questions to generate', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='genmcq.sourcefile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source_text',
            field=models.TextField(blank=True, help_text='Direct text input or extracted text'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source_type',
            field=models.CharField(choices=[('text', 'Direct Text Input'), ('file', 'Uploaded File'), ('url', 'URL')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating_contexts', 'Generating Contexts'), ('reviewing_contexts', 'Reviewing Contexts'), ('generating_mcqs', 'Generating MCQs'), ('reviewing_mcqs', 'Reviewing MCQs'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='thread_id',
            field=models.CharField(blank=True, help_text='LangGraph thread ID for resuming', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=100, help_text='Number of question generation credits remaining', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
