review_context_prompt = """
Critically evaluate the provided analytical context, which was generated to serve as the basis for a multiple-choice question. The evaluation should be based on the standards and criteria outlined in the original context generation prompt.

**Given:**

1.  **CONTEXT_TO_REVIEW:** The analytical narrative generated by the AI.
    ```text
    {context_gen}
    ```
        
2.  **SOURCE_MATERIALS:** The original inputs used for generation, including:
    *   **LECTURE_CONTENT:**
        ```text
        {text}
        ```
    *   **SUBJECT_TOPIC:** `{subject} - {topic}`
    *   **KEY_POINT:** `{key_point}`
    *   **SOLVED_EXERCISES (if any):**
        ```text
        {{exercises}}
        ```
    *   **BLOOM_LEVEL:** `{bloom_level}` The target cognitive level for the context.

**Your task:**

Your primary goal is to assess whether the generated context is a **sufficient and focused foundation** for creating **a single, high-quality multiple-choice question** at the specified `BLOOM_LEVEL`. You should not penalize the context for being brief, as long as it contains the necessary depth for this specific purpose.

You must assess the context against the following critical criteria.

**Evaluation Criteria:**

1.  **Analytical Depth vs. Bloom's Level:**
    *   Assess if the analytical depth and complexity are **sufficient and appropriate** to support the creation of **at least one challenging question** at the specified `BLOOM_LEVEL`. The context does not need to be exhaustive; it needs to be **fit-for-purpose**.

2.  **Nature of the Narrative (Analysis, Not Command):**
    *   Assess whether the context is a self-contained **analytical narrative** ("the analysis itself") rather than a descriptive summary or a command to analyze.

3.  **Focused and Sufficient Analysis:**
    *   Verify that the context provides a **focused and sufficient analytical path for one question**. This could be a step-by-step deconstruction of a core concept, the application of a formula, or the exploration of a **single, relevant 'what-if' scenario**. The goal is to provide a clear foundation for one question, not to cover all possibilities.
    *   **CRITICAL CONSTRAINT:** Do NOT suggest improvements for minor stylistic choices or phrasing if the analytical logic is sound and fits the Bloom level. If the content is "good enough" to create a question, it should pass.

4.  **Integrity and Integration of Core Objects:**
    *   Check if all relevant **Core Objects** (e.g., formulas, definitions) from the source material are included **verbatim** and are seamlessly integrated into the flow of the analysis.

5.  **Clarity, Language, and Structural Integrity:**
    *   Ensure the Vietnamese is professional, clear, and that the context **does not contain any questions**.

**Output Format:**

Provide your feedback in the following structured format. Be direct and provide concrete examples.

**Evaluation:**
[Provide a concise, overall summary of the context's strengths and weaknesses based on the five criteria above. For instance: "Nội dung đã bảo toàn được công thức cốt lõi và cung cấp đủ chiều sâu để tạo một câu hỏi ở cấp độ 'Vận dụng'. Tuy nhiên, phân tích còn hơi lan man và có thể tập trung hơn vào một khía cạnh duy nhất để tăng hiệu quả."]

**Actionable Suggestions:**
[This section serves a dual purpose:
*   **CASE 1:If the context can be improved:** Provide a bulleted list of specific, actionable recommendations. Your suggestions must be concrete and guide the AI on how to enhance the context to be **more focused and effective** for generating a single question.
*   **CASE 2:The context is sufficient (Fit-for-purpose):Do not add any other words, punctuation, or explanations in this section if it is done.

**Examples for providing suggestions:**
*   **Depth/Focus: "Để tạo một câu hỏi 'Phân tích' hiệu quả, nội dung nên tập trung hoàn toàn vào việc phân tích các thành phần của biệt thức (b²-4ac) và giải thích cách nó quyết định tính chất của nghiệm, thay vì chỉ áp dụng công thức."
*   **Focused Analysis: "Phân tích hiện tại còn thụ động. Hãy thay thế nó bằng một kịch bản duy nhất: 'Xét trường hợp hệ số 'c' dương, ví dụ phương trình 2x² + 5x + 3 = 0. Khi đó, biệt thức sẽ...' và chỉ cần đi sâu vào phân tích kết quả mới này."
*   **Clarity: "Để làm cho lộ trình phân tích rõ ràng hơn cho một câu hỏi, hãy viết lại bước 3 để chỉ tập trung vào mối liên hệ nhân quả giữa áp suất tăng và sự dịch chuyển cân bằng."]"""
################################################################################################################################################

review_mcq_prompt = """Critically evaluate the provided Multiple-Choice Question (MCQ) package. Your evaluation must be based on the rigorous standards, rules, and pedagogical tactics outlined in the original question generation prompt (`prompt_gen_mcqs`).

Your goal is to act as a quality control expert, ensuring that every component of the question (stem, options, and rationale) is pedagogically sound, structurally correct, and cognitively challenging at the intended level.

**Given:**

1.  **MCQ_TO_REVIEW:**  {mcq}The complete JSON object of the question to be evaluated.
2.  **ORIGINAL_CONTEXT:** {context}The analytical context provided for the question's creation.
3.  **BLOOM_LEVEL:** {bloom_level} The target Bloom's Taxonomy level for the question.

**Evaluation Framework:**
*   **Zero Tolerance for Spoon-Feeding:** Unless the level is "Remember", any definition provided in the stem is a defect.
*   **Tactic Enforcement:** High-level questions must use multiple design tactics, not just one.
*   **Constructive Rigor:** You must provide specific instructions to "harden" the question if it is too easy.
You must meticulously assess the MCQ against the following criteria, which are derived directly from the generation prompt's core requirements.

---

### **Part 1: The "Spoon-Feeding" & Content Check (Conditional Logic)**
**1.1. Check for Banned "Meta-References" (CRITICAL):**
    Scan the Stem for any phrases referring to the text itself.
    *   **BANNED LIST:** "Theo ngữ cảnh", "Dựa vào đoạn văn", "Như đã nêu", "Trong tài liệu", "Căn cứ vào", "Theo tác giả", "Thông tin trên cho thấy"...
    *   **ACTION:** If ANY of these exist -> **FAIL**.
    *   **Requirement:** The Stem must treat the information as objective facts, not as "content from a text".
        *   *Bad:* "Theo đoạn văn, khi nhiệt độ tăng thì..."
        *   *Good:* "Khi nhiệt độ tăng..."
        
**1.2. Check the `bloom_level` and apply the corresponding rule:**

    *   **SCENARIO A: If `bloom_level` == "Remember" (Nhớ)**
        *   **Rule:** The stem MAY contain definitions, state laws explicitly, or ask for direct identification.
        *   **Check:** Is the fact accurate based on the context?
        *   **Pass Condition:** The question tests precise recall of key facts/terms.

    *   **SCENARIO B: If `bloom_level` >= "Understand" (Hiểu, Vận dụng, Phân tích...)**
        *   **Rule 1 (The "Name-Drop" Rule):** Does the stem define or explain a term? (e.g., "Gia tốc, là đại lượng..."). **If YES -> FAIL immediately.** The stem must uses technical terms *without* explanation, assuming prior mastery.
        *   **Rule 2 (No Giveaways):** Does the stem provide formulas or constants that should be prerequisite knowledge? (Unless it's a specific "Analyze a *new* formula" task). **If YES -> FAIL.**
        *   **Rule 3 (Scenario-Based):** Does the stem start immediately with a scenario/problem ("Một vật đang trượt...") instead of meta-talk ("Dựa vào kiến thức...")?

### **Part 2: Complexity & Tactic Stacking (For "Understand" and above)**

*   **2.1. Tactic Combination:**
    *   Read the `tactic_analysis`. Does it explicitly list a **combination of at least 2 tactics**? (e.g., "Scenario" + "Extraneous Info" OR "Reverse Reasoning" + "Trap Assumptions").
    *   **Action:** If it relies on a single, simple tactic -> **Mark as Weak**.
*   **2.2. Execution Reality:**
    *   Does the Stem *actually perform* these tactics?
    *   *Example:* If the analysis claims "Extraneous Information", is there actually data in the stem that must be ignored?

### **Part 3: Options & Distractor Quality (The "Trap" Check)**

*   **3.1. Plausibility:** Are the distractors "seductive"? Do they look correct to a student who knows the keywords but lacks deep understanding?
*   **3.2. Error Mapping:**
    *   Does each distractor in `distractor_justification` correspond to a **Specific Hard Error** (e.g., Common Misconception, Unit Conversion Error, Wrong Condition)?
    *   **Fail Condition:** If a distractor is justified merely as "A random wrong number" or "Unrelated fact".

### **Part 4: Rationale Alignment**
*   **4.1. Bloom Accuracy:** Does the cognitive task match the label? (e.g., Label is "Analyze", but the task is just "Recall" -> Fail).
*   **4.2. Logic:** Is the explanation for the Correct Answer factually sound?

---

**Output Format:**

Provide your feedback in the following single, structured format.

**Evaluation:**
[Provide a concise, overall summary of the MCQ's strengths and weaknesses, covering all its components (stem, options, and rationale). For example: "Phần thân câu hỏi được xây dựng tốt và tuân thủ đầy đủ các quy tắc nội dung. Tuy nhiên, các phương án nhiễu không có giá trị sư phạm vì quá dễ nhận ra, và phần giải thích cho cấp độ Bloom chưa đủ thuyết phục."]

**Actionable Suggestions:**
[This section determines the next step. Follow these rules STRICTLY:
*   **CASE 1: The MCQ is flawed/invalid:**
    *   If the **Stem** is unclear or violates the "No Vague References" rule.
    *   If the **Key** is wrong or ambiguous.
    *   If the **Distractors** are nonsensical or confusing (not just "too easy").
    *   -> Provide concrete instructions to fix these specific fatal errors.

*   **CASE 2: The MCQ is valid and usable (Fit-for-purpose):**
    *   If the Stem and Options are logically sound and pedagogically acceptable (even if not "perfect").
    *   Do not add any other words, punctuation, or explanations in this section if it is done

**Examples for providing suggestions:**
*   "**Stem:** Viết lại câu thứ hai để đưa công thức 'U = IR' nguyên văn thay vì chỉ nêu tên công thức."
*   "**Options:** Thay phương án nhiễu C bằng một đáp án xuất phát từ lỗi đổi đơn vị thường gặp (ví dụ: quên đổi từ gam sang kilogam)."
*   "**Rationale:** Sửa phần bloom_level_analysis để giải thích chính xác hơn tại sao nhiệm vụ này yêu cầu 'Phân tích' chứ không chỉ là 'Vận dụng'."
]
"""

################################################################################################################################################

review_distractor_prompt = """
Task: Analyze and enhance the provided distractors, which were generated based on {type} error type, to maximize their difficulty and deceptiveness while ensuring they remain incorrect.

Given:
    1. A context relevant to question
    2. A question about the context
    3. The correct answer
    4. A set of distractor options for a specific error type (e.g., reasoning error, question bias, etc.)
    5. The reasoning provided for why each distractor was created

For each distractor, your task is to:
    1. Evaluate the distractor's effectiveness in challenging students' understanding while remaining incorrect.
    2. Assess how well the distractor aligns with the {type} error and the given contex.
    3. Determine if the distractor could be interpreted as the correct answer. If so, add suggestions towards this.
    4. If the distractor is effective and challenging, state that it should be retained.
    5. If improvements are needed, provide specific suggestions to increase the distractor's difficulty and deceptiveness without:
        a. Increasing the option's length or adding unnecessary modifiers
        b. Making the distractor correct
    6. Ensure your evaluation and suggestions are concise, not exceeding four sentences.

Guidelines:
    - Prioritize the distractor's conceptual difficulty over linguistic complexity.
    - If a distractor is correct or could be interpreted as correct, clearly state this and suggest how to modify it to make it unambiguously incorrect.
    - Focus on enhancing the distractor's plausibility within the context of the {type} error and the context.
    - Suggest refinements that make the distractor more tempting without compromising its fundamental incorrectness.
    - Ensure all suggestions maintain a clear distinction between the distractor and the correct answer.

For each option, format your response as:
    Option:
        option: [Option text]
        comment: [Your evaluation and specific suggestions, if needed, or confirmation of effectiveness]
"""

